// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	"github.com/rs/zerolog/log"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MovieServiceClient is the client API for MovieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieServiceClient interface {
	CreateMovie(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DescribeMovie(ctx context.Context, in *DescribeMovieMessage, opts ...grpc.CallOption) (*Movie, error)
	RemoveMovie(ctx context.Context, in *RemoveMovieMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListMovies(ctx context.Context, in *MovieListRequest, opts ...grpc.CallOption) (*MovieList, error)
}

type movieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieServiceClient(cc grpc.ClientConnInterface) MovieServiceClient {
	return &movieServiceClient{cc}
}

func (c *movieServiceClient) CreateMovie(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	log.Print("CreateMovie performed")
	out := new(emptypb.Empty)
	return out, nil
}

func (c *movieServiceClient) DescribeMovie(ctx context.Context, in *DescribeMovieMessage, opts ...grpc.CallOption) (*Movie, error) {
	out := new(Movie)
	log.Print("DescribeMovie performed")
	return out, nil
}

func (c *movieServiceClient) RemoveMovie(ctx context.Context, in *RemoveMovieMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	log.Print("RemoveMovie performed")
	return out, nil
}

func (c *movieServiceClient) ListMovies(ctx context.Context, in *MovieListRequest, opts ...grpc.CallOption) (*MovieList, error) {
	out := new(MovieList)
	log.Print("ListMovies performed")
	return out, nil
}

// MovieServiceServer is the server API for MovieService service.
// All implementations must embed UnimplementedMovieServiceServer
// for forward compatibility
type MovieServiceServer interface {
	CreateMovie(context.Context, *Movie) (*emptypb.Empty, error)
	DescribeMovie(context.Context, *DescribeMovieMessage) (*Movie, error)
	RemoveMovie(context.Context, *RemoveMovieMessage) (*emptypb.Empty, error)
	ListMovies(context.Context, *MovieListRequest) (*MovieList, error)
	mustEmbedUnimplementedMovieServiceServer()
}

// UnimplementedMovieServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMovieServiceServer struct {
}

func (UnimplementedMovieServiceServer) CreateMovie(context.Context, *Movie) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMovie not implemented")
}
func (UnimplementedMovieServiceServer) DescribeMovie(context.Context, *DescribeMovieMessage) (*Movie, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeMovie not implemented")
}
func (UnimplementedMovieServiceServer) RemoveMovie(context.Context, *RemoveMovieMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMovie not implemented")
}
func (UnimplementedMovieServiceServer) ListMovies(context.Context, *MovieListRequest) (*MovieList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMovies not implemented")
}
func (UnimplementedMovieServiceServer) mustEmbedUnimplementedMovieServiceServer() {}

// UnsafeMovieServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieServiceServer will
// result in compilation errors.
type UnsafeMovieServiceServer interface {
	mustEmbedUnimplementedMovieServiceServer()
}

func RegisterMovieServiceServer(s grpc.ServiceRegistrar, srv MovieServiceServer) {
	s.RegisterService(&MovieService_ServiceDesc, srv)
}

func _MovieService_CreateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Movie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).CreateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova_film_api.MovieService/createMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).CreateMovie(ctx, req.(*Movie))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_DescribeMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeMovieMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).DescribeMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova_film_api.MovieService/describeMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).DescribeMovie(ctx, req.(*DescribeMovieMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_RemoveMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMovieMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).RemoveMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova_film_api.MovieService/removeMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).RemoveMovie(ctx, req.(*RemoveMovieMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_ListMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).ListMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova_film_api.MovieService/listMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).ListMovies(ctx, req.(*MovieListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieService_ServiceDesc is the grpc.ServiceDesc for MovieService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ova_film_api.MovieService",
	HandlerType: (*MovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createMovie",
			Handler:    _MovieService_CreateMovie_Handler,
		},
		{
			MethodName: "describeMovie",
			Handler:    _MovieService_DescribeMovie_Handler,
		},
		{
			MethodName: "removeMovie",
			Handler:    _MovieService_RemoveMovie_Handler,
		},
		{
			MethodName: "listMovies",
			Handler:    _MovieService_ListMovies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
